name: new_big_data
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - arrow-cpp=19.0.0=hb704434_4
  - asttokens=3.0.1=pyhd8ed1ab_0
  - aws-c-auth=0.9.0=h11bee3c_15
  - aws-c-cal=0.9.2=h80a239a_0
  - aws-c-common=0.12.3=h6e16a3a_0
  - aws-c-compression=0.3.1=hdea44ad_5
  - aws-c-event-stream=0.5.5=h01412b5_0
  - aws-c-http=0.10.2=ha1444c5_2
  - aws-c-io=0.20.1=h550966a_1
  - aws-c-mqtt=0.13.1=h90c2deb_3
  - aws-c-s3=0.8.3=hb3f0f26_0
  - aws-c-sdkutils=0.2.4=hdea44ad_0
  - aws-checksums=0.2.7=hdea44ad_1
  - aws-crt-cpp=0.32.10=h0dd05b8_2
  - aws-sdk-cpp=1.11.528=he026a02_1
  - boost-cpp=1.78.0=h179ae3a_0
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h1854d6b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - gflags=2.2.2=hac325c4_1005
  - glog=0.5.0=h25b26a9_0
  - icu=70.1=h96cf925_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libabseil=20250127.0=cxx17_h0e468a2_0
  - libblas=3.11.0=2_he492b99_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_9
  - libbrotlidec=1.0.9=hb7f2c08_9
  - libbrotlienc=1.0.9=hb7f2c08_9
  - libcblas=3.11.0=2_h9b27e0a_openblas
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libffi=3.4.4=hecd8cb5_1
  - libgcc=15.2.0=h08519bb_12
  - libgfortran=15.2.0=h7e5c614_12
  - libgfortran5=15.2.0=hd16e46c_12
  - libgrpc=1.71.0=hf2926fd_0
  - liblapack=3.11.0=2_h859234e_openblas
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libprotobuf=5.29.3=h66a43dd_1
  - libre2-11=2024.07.02=h08ce7b7_3
  - libsodium=1.0.20=hfdf4475_0
  - libssh2=1.11.1=h3a17b82_0
  - libthrift=0.15.0=h70b4b81_2
  - llvm-openmp=19.1.7=ha54dae1_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.5=py311hf157cb9_0
  - openjdk=17.0.14=h46256e1_0
  - openssl=3.6.0=h230baf5_0
  - orc=2.1.1=h4dda5a6_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hca9a5ca_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311h62e9434_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py4j=0.10.9.9=pyhd8ed1ab_0
  - pyarrow=19.0.0=py311h6d0c2b6_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyspark=4.0.1=pyhd8ed1ab_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py311h0ab6910_0
  - re2=2024.07.02=hf8a452e_3
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h01f5ddf_1
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.2=py311hf197a57_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - utf8proc=2.6.1=h6c40b1e_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.60.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - pillow==12.0.0
      - pyparsing==3.2.5
      - seaborn==0.13.2
prefix: /Users/kvt/miniconda3/envs/new_big_data
